spring.application.name=ecommerce

#banco configs

# 1 - usurio
spring.datasource.username=root
# 2 - senha
spring.datasource.password=murillo97
# 3 - url
spring.datasource.url=jdbc:mysql://localhost:3306/db_bijoux?useTimezone=true&serverTimezone=UTC
# 4 - dialeto
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
# 5 - SQL instrucoes
spring.jpa.show_sql=true
